### ISSUE TITLE
IsaacGymEnvs/isaacgymenvsのpython3 train.pyが実行できない問題

### ISSUE THREAD

**Issue by HarukiOgawa1** [open-rdc/IsaacGym_Wiki#2]
```
python3 train.py task=Cartpole
```
を実行しようとしたところ以下のエラーが発生した．
```
(rlgpu) harukiogawa@HayashibaraLab-ML3:~/IsaacGymEnvs/isaacgymenvs$ python3 train.py task=Cartpole
/home/harukiogawa/anaconda3/envs/rlgpu/lib/python3.7/site-packages/hydra/_internal/hydra.py:127: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  configure_logging=with_log_configuration,
Importing module 'gym_37' (/home/harukiogawa/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_37.so)
Setting GYM_USD_PLUG_INFO_PATH to /home/harukiogawa/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
Error executing job with overrides: ['task=Cartpole']
Traceback (most recent call last):
  File "train.py", line 80, in launch_rlg_hydra
    from isaacgymenvs.pbt.pbt import PbtAlgoObserver, initial_pbt_check
  File "/home/harukiogawa/IsaacGymEnvs/isaacgymenvs/pbt/pbt.py", line 39, in <module>
    import torch
  File "/home/harukiogawa/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
ImportError: /home/harukiogawa/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

anaconda上のPackageのVersion　一部省略
```
(rlgpu) harukiogawa@HayashibaraLab-ML3:~/IsaacGymEnvs/isaacgymenvs$ pip list
Package                 Version     Editable project location
----------------------- ----------- ---------------------------------
gym                     0.23.1
gym-notices             0.0.8
hydra-core              1.3.2
isaacgym                1.0rc4      /home/harukiogawa/isaacgym/python
isaacgymenvs            1.5.1       /home/harukiogawa/IsaacGymEnvs
numpy                   1.21.6
opencv-python           4.9.0.80
pip                     24.0
pycollada               0.6
pycparser               2.21
pyglet                  2.0.10
PyJWT                   2.8.0
PyOpenGL                3.1.0
pyOpenSSL               23.2.0
python-dateutil         2.9.0.post0
rl-games                1.6.1
rsa                     4.9
scipy                   1.7.3
sentry-sdk              2.2.0
setproctitle            1.3.3
setuptools              69.0.3
shortuuid               1.0.13
six                     1.16.0
smmap                   5.0.1
tensorboard             2.11.2
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorboardX            2.6.2.2
termcolor               2.3.0
torch                   1.8.1
torchvision             0.9.1
```

**Comment by YugoNishio** [comment]
おそらくですが、CUDAとpytorchのバージョンが合っていません。
また、isaacgymのライブラリはpython3.6、3.7あたりで動作します。
まずはCUDAのバージョンがそれに合っているか確認してみてください。

**Comment by HarukiOgawa1** [comment]
CUDAのバージョンを確認しました
```
nvcc --version
```
![image](https://github.com/open-rdc/IsaacGym_Wiki/assets/71487953/07797402-6a59-4d58-b9ea-28121e945713)

![スクリーンショット 2024-05-18 213137](https://github.com/open-rdc/IsaacGym_Wiki/assets/71487953/71aad07d-967f-43ca-9046-f28713b9d8df)

**Comment by yasuohayashibara** [comment]
nvidia-smiのバージョンは実際にインストールされているバージョンとは異なります．
紛らわしいですが．．．

https://zenn.dev/takeshita/articles/a02402e59d72a7

**Comment by HarukiOgawa1** [comment]
とりあえず，CUDAとpytorchのバージョンの問題はDockerで環境構築することで解決しました．
以下を参考にした．
https://valinux.hatenablog.com/entry/20240111
