### ISSUE TITLE
Dockerを用いた環境構築の記録

### ISSUE THREAD

**Issue by HarukiOgawa1** [open-rdc/IsaacGym_Wiki#3]
DockerでIsaac Gymを環境構築する記録（メモ）
実行環境
- Ubuntu 20.04
- NVIDIA driver version 550.54.15
- GeForce RTX 2080 Super

以下を参考に行う．
https://valinux.hatenablog.com/entry/20240111

**Comment by HarukiOgawa1** [comment]
参考に従って環境のCUDA versionは以下である．
```
gymuser@HayashibaraLab-ML3:/gymworkspace/IsaacGymEnvs/isaacgymenvs$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Aug_15_21:14:11_PDT_2021
Cuda compilation tools, release 11.4, V11.4.120
Build cuda_11.4.r11.4/compiler.30300941_0
```

**Comment by HarukiOgawa1** [comment]
以下は
/gymworkspace/IsaacGymEnvs/isaacgymnvs$ python3 train.py task=Ant を実行したら出てきたターミナル画面（長いです）．

```
gymuser@HayashibaraLab-ML3:/gymworkspace/IsaacGymEnvs/isaacgymenvs$ python3 train.py task=Ant
/home/gymuser/.local/lib/python3.8/site-packages/hydra/_internal/hydra.py:119: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  ret = run_job(
Importing module 'gym_38' (/gymworkspace/isaacgym/python/isaacgym/_bindings/linux-x86_64/gym_38.so)
Setting GYM_USD_PLUG_INFO_PATH to /gymworkspace/isaacgym/python/isaacgym/_bindings/linux-x86_64/usd/plugInfo.json
PyTorch version 1.10.0a0+3fd9dcf
Device count 2
/gymworkspace/isaacgym/python/isaacgym/_bindings/src/gymtorch
Using /home/gymuser/.cache/torch_extensions/py38_cu114 as PyTorch extensions root...
Emitting ninja build file /home/gymuser/.cache/torch_extensions/py38_cu114/gymtorch/build.ninja...
Building extension module gymtorch...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module gymtorch...
2024-05-26 12:31:35,152 - INFO - logger - logger initialized
/gymworkspace/IsaacGymEnvs/isaacgymenvs/tasks/amp/poselib/poselib/core/rotation3d.py:222: DeprecationWarning: invalid escape sequence \*
  """
Error: FBX library failed to load - importing FBX data will not succeed. Message: No module named 'fbx'
FBX tools must be installed from https://help.autodesk.com/view/FBX/2020/ENU/?guid=FBX_Developer_Help_scripting_with_python_fbx_installing_python_fbx_html
/gymworkspace/isaacgym/python/isaacgym/torch_utils.py:135: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def get_axis_params(value, axis_idx, x_value=0., dtype=np.float, n_dims=3):
/home/gymuser/.local/lib/python3.8/site-packages/networkx/classes/graph.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping
/home/gymuser/.local/lib/python3.8/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Mapping, Set, Iterable
/home/gymuser/.local/lib/python3.8/site-packages/networkx/readwrite/graphml.py:346: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (np.int, "int"), (np.int8, "int"),
task: 
    name: Ant
    physics_engine: physx
    env: 
        numEnvs: 4096
        envSpacing: 5
        episodeLength: 1000
        enableDebugVis: False
        clipActions: 1.0
        powerScale: 1.0
        controlFrequencyInv: 1
        headingWeight: 0.5
        upWeight: 0.1
        actionsCost: 0.005
        energyCost: 0.05
        dofVelocityScale: 0.2
        contactForceScale: 0.1
        jointsAtLimitCost: 0.1
        deathCost: -2.0
        terminationHeight: 0.31
        plane: 
            staticFriction: 1.0
            dynamicFriction: 1.0
            restitution: 0.0
        asset: 
            assetFileName: mjcf/nv_ant.xml
        enableCameraSensors: False
    sim: 
        dt: 0.0166
        substeps: 2
        up_axis: z
        use_gpu_pipeline: True
        gravity: [0.0, 0.0, -9.81]
        physx: 
            num_threads: 4
            solver_type: 1
            use_gpu: True
            num_position_iterations: 4
            num_velocity_iterations: 0
            contact_offset: 0.02
            rest_offset: 0.0
            bounce_threshold_velocity: 0.2
            max_depenetration_velocity: 10.0
            default_buffer_size_multiplier: 5.0
            max_gpu_contact_pairs: 8388608
            num_subscenes: 4
            contact_collection: 0
    task: 
        randomize: False
        randomization_params: 
            frequency: 600
            observations: 
                range: [0, 0.002]
                operation: additive
                distribution: gaussian
            actions: 
                range: [0.0, 0.02]
                operation: additive
                distribution: gaussian
            actor_params: 
                ant: 
                    color: True
                    rigid_body_properties: 
                        mass: 
                            range: [0.5, 1.5]
                            operation: scaling
                            distribution: uniform
                            setup_only: True
                    dof_properties: 
                        damping: 
                            range: [0.5, 1.5]
                            operation: scaling
                            distribution: uniform
                        stiffness: 
                            range: [0.5, 1.5]
                            operation: scaling
                            distribution: uniform
                        lower: 
                            range: [0, 0.01]
                            operation: additive
                            distribution: gaussian
                        upper: 
                            range: [0, 0.01]
                            operation: additive
                            distribution: gaussian
train: 
    params: 
        seed: 42
        algo: 
            name: a2c_continuous
        model: 
            name: continuous_a2c_logstd
        network: 
            name: actor_critic
            separate: False
            space: 
                continuous: 
                    mu_activation: None
                    sigma_activation: None
                    mu_init: 
                        name: default
                    sigma_init: 
                        name: const_initializer
                        val: 0
                    fixed_sigma: True
            mlp: 
                units: [256, 128, 64]
                activation: elu
                d2rl: False
                initializer: 
                    name: default
                regularizer: 
                    name: None
        load_checkpoint: False
        load_path: 
        config: 
            name: Ant
            full_experiment_name: Ant
            env_name: rlgpu
            multi_gpu: False
            ppo: True
            mixed_precision: True
            normalize_input: True
            normalize_value: True
            value_bootstrap: True
            num_actors: 4096
            reward_shaper: 
                scale_value: 0.01
            normalize_advantage: True
            gamma: 0.99
            tau: 0.95
            learning_rate: 0.0003
            lr_schedule: adaptive
            schedule_type: legacy
            kl_threshold: 0.008
            score_to_win: 20000
            max_epochs: 500
            save_best_after: 200
            save_frequency: 50
            grad_norm: 1.0
            entropy_coef: 0.0
            truncate_grads: False
            e_clip: 0.2
            horizon_length: 16
            minibatch_size: 32768
            mini_epochs: 4
            critic_coef: 2
            clip_value: True
            seq_len: 4
            bounds_loss_coef: 0.0001
pbt: 
    enabled: False
task_name: Ant
experiment: 
num_envs: 
seed: 42
torch_deterministic: False
max_iterations: 
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: False
checkpoint: 
sigma: 
multi_gpu: False
wandb_activate: False
wandb_group: 
wandb_name: Ant
wandb_entity: 
wandb_project: isaacgymenvs
wandb_tags: []
wandb_logcode_dir: 
capture_video: False
capture_video_freq: 1464
capture_video_len: 100
force_render: True
headless: False
Setting seed: 42
Using rl_device: cuda:0
Using sim_device: cuda:0
{'name': 'Ant', 'full_experiment_name': None, 'env_name': 'rlgpu', 'multi_gpu': False, 'ppo': True, 'mixed_precision': True, 'normalize_input': True, 'normalize_value': True, 'value_bootstrap': True, 'num_actors': 4096, 'reward_shaper': {'scale_value': 0.01}, 'normalize_advantage': True, 'gamma': 0.99, 'tau': 0.95, 'learning_rate': 0.0003, 'lr_schedule': 'adaptive', 'schedule_type': 'legacy', 'kl_threshold': 0.008, 'score_to_win': 20000, 'max_epochs': 500, 'save_best_after': 200, 'save_frequency': 50, 'grad_norm': 1.0, 'entropy_coef': 0.0, 'truncate_grads': False, 'e_clip': 0.2, 'horizon_length': 16, 'minibatch_size': 32768, 'mini_epochs': 4, 'critic_coef': 2, 'clip_value': True, 'seq_len': 4, 'bounds_loss_coef': 0.0001, 'device': 'cuda:0', 'population_based_training': False, 'pbt_idx': None}
self.seed = 42
Error executing job with overrides: ['task=Ant']
Traceback (most recent call last):
  File "train.py", line 206, in launch_rlg_hydra
    os.makedirs(experiment_dir, exist_ok=True)
  File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: 'runs/Ant_26-12-31-35'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
gymuser@HayashibaraLab-ML3:/gymworkspace/IsaacGymEnvs/isaacgymenvs$ 

```

**Comment by HarukiOgawa1** [comment]
IsaacLabでやることにしたため閉じる．
